# Hardware configuration for Innovation Core microscope with LDI Polygon
backend_configuration:
  backend_name: "pycromanager"
  mm_config_path: "C:\\Program Files\\Micro-Manager-2.0\\InnovationCore_Config.cfg"
  microscope_name: "innovation core spinning disk"

stimulus_configuration:
  stim_interface: "InvCore-LDI-Polygon-640"

# Stimulus device configurations
stimulus_devices:
  InvCore-LDI-Polygon-640:
    type: "polygon"
    intensity_device: "89 North Laser Diode Illuminator"
    intensity_property: "640 Intensity"
    shutter_device: "89 North Laser Diode Illuminator"
    slm_device: null  # Will query from MMC
    
    # Calibration of DMD
    # polygon_calibration_path: "./hardware/stimulus_controllers/stimulus_resources/Mightex Polygon P1000/calibrations.json"
    polygon_calibration_path: "C:/Users/Leica/code/clef/hardware/stimulus_controllers/stimulus_resources/MightexPolygon1000/calibrations.json"

  InvCore-SpinningDisk-639:
    type: "widefield_laser"
    voltage_device: "DAC639"
    voltage_property: "Volts"
    ttl_device: "TTL1-8"
    ttl_line: "TTL-4"
    max_volts: 3.5

# Device configurations
system_devices:
  camera:
    device_name: "PrimeBSI"
    device_type: "camera"
    properties:
      Exposure: 10.0
      Binning: "1x1"
  
  stage:
    # XYStage:
    #   device_name: "XYStage"
    #   device_type: "stage"
    #   configs: {}

    # ZStage: 
    # todo because we have multiple types of stages, we could either just have "stage" and interpret based on name/type, or we could have multiple stage subtypes like "zstage" and "xystage"
    # in our hardware_demo, we have an xyz stage, but we only need to control z...
    device_name: "ZStage"
    device_type: "stage"
    configs: {}
    properties: {}
    ttl_device: "TTL1-8"
    ttl_state: "18"
    z_step_size_um: 2.5
    num_z_planes: 12

  # Illumination channels
  illumination_channels:
    - name: "dummy"
      device: "dummy"
      wavelength: null
      power: 50.0
      exposure_ms: 100.0

      # Strobe settings
      strobe_illumination: false
      strobe_inter_frame_interval_ms: 80 # not used if strobe_acquisition is false

# System properties
system_properties:

  # Microscope name (temporary, backward compatibility)
  system_name: 'InnovationCoreSpinningDisk'
  auto_shutter: false
  circular_buffer_mb: 10000
  # configs:
  #   Channel: "488"
  shutters:
    - device_name: "89 North Laser Diode Illuminator"
      state: true

