# Physical Hardware Demo IO Configuration
# Innovation Core spinning disk microscope with Mightex Polygon + 89 North LDI

input_devices:
  - input_device_name: "camera"
    input_device_type: "camera"
    input_device_class: "micromanager_camera"
    data_interface_class: "shm_uint16_data_interface"
    data_interface_parameters:
      shm_buffer_size: 6 # should be same as stage output device zsize
      shm_name_prefix: "shared_frame_memory" # produces shared_frame_memory_0, ..., shared_frame_memory_image_count
    input_device_parameters:
      device_properties: null # No extra device properties to set
      use_strobed_acquisition: true
      strobe_inter_frame_interval_ms: 160.0

output_devices:
  - output_device_name: "z_stage"
    output_device_type: "stage"
    output_device_class: "micromanager_stage"
    output_device_parameters:
      z_step_size_um: 3
      num_z_planes: 6
      ttl_device: "TTL1-8"
      ttl_state: "22" # 18 for gcamp + stage (ttl2+, ttl5+). 20 for rfp + stage (ttl3+, ttl5+). 22 for gfp+rfp (ttl2+, ttl3+, ttl5+)

  - output_device_name: "polygon"
    output_device_type: "dmd"
    output_device_class: "mightex_polygon"
    output_device_parameters:
      slm_device: null # will query from Micro-Manager

  - output_device_name: "ldi"
    output_device_type: "lightsource"
    output_device_class: "ldi_89north"
    output_device_parameters:
      intensity_device: "89 North Laser Diode Illuminator"
      intensity_property: "470 Intensity"
      shutter_device: "89 North Laser Diode Illuminator"
