# CLEF Minimal Closed-Loop Logic Configuration

# Algorithm selection
logic_algorithm: ""  #

# Algorithm-specific parameters
logic_parameters: {}

# Trigger-related algorithm parameters
io_parameters:

  # List of output devices that the logic can trigger
  output_devices:
    - output_device_name: null
      output_device_type: null
      output_parameters: {}
      output_enabled: false

  input_devices:
    - input_device_name: null
      input_device_type: null
      input_parameters: {}
      input_enabled: false

# GUI settings, if applicable to the logic/algorithm
gui_parameters:
  enable_gui: false
  gui_mode: "none"  # Options: neural_imaging, behavior, none